Update: Test Publish (#11)
* Feature v1.0.0 alpha 6 (#6)

* Chore: Publish Testing

* Update: Automated Package Version Update

* Chore: Update packages

* Chore: Test Publishing

* Chore: Test Publishing

* Chore: Test Publishing

* Chore: Test Publishing

---------

Co-authored-by: deejaygeroso <deejaygeroso@users.noreply.github.com>

* Update: Automated Package Version Update

* Update: Packages

* Chore: Test Publishing

* Update: Automated Package Version Update

* Chore: Test Publishing

* Update: Changeset Origin

* Chore: Test Publishing

* Update: Automated Package Version Update

* Chore: Test Publishing

* Update: Automated Package Version Update

* Chore: Test Publishing

* Chore: Test Publishing

* Chore: Test Publishing

* Chore: Add script

* Chore: Update Pipeline

* Chore: Remove changesets

* Chore: Test Publish

* Chore: Test Publish

* Chore: Test Publish

* Update: Automated Package Version Update

* Chore: Test Changeset

* Chore: Test Changeset

* Chore: Test Changeset

* Chore: Test Changeset

* Chore: Test Changeset

* Chore: Test Changeset

* Chore: Test Changeset

* Chore: Test Changeset

* Chore: Test Changeset

* Chore: Test Changeset

* Chore: Test Changeset

* Chore: Test Changeset

* Chore: Test Changeset

* Chore: Add ci:publish

* Chore: Test Changeset

* Update: .npmrc

* Update: UI Updated

* Chore: Test without Token

* Update: Test without Token

* Chore: Add invalid token

* Update: Add Valid TOken

* Update: Package update

* Update: Release Pipeline Updated

* Update: Setup auth token

* Update: Remove duplicate

* Update: List all Files

* Update: Changeset Status

* Chore: Test

* Chore: Test

* Chore: Test

* Chore: Test

* Chore: Test

* Chore: Test

* Chore: Test

* Chore: Test Publish

* Chore: Add env file

* Chore: Test Publish

* Chore: Test Publish

* Chore: Test Publish

* Chore: Test Publish

* Update: Test Publish

* Update: workspace

* Update: Package

* Update: Package

* Chore: Set pnpm workspace

* Chore: Release Pipeline updated

* Update: dist directory

* Chore: Add changeset

* Chore: Publish Package

* Chore: lockfile updated

* Chore: Test GitHub ACtions

* Chore: Test GitHub ACtions

* Chore: Test GitHub Actions

* Chore: Test GitHub Actions

* Chore: Test GitHub Actions

* Chore: Test GitHub Actions

* Chore: Test GitHub Actions

* Chore: Test GitHub Actions

* Chore: Test GitHub Actions

* Chore: Test GitHub Actions

* Chore: Test GitHub Actions

* Chore: Test GitHub Actions

* Chore: Test GitHub Actions

* Chore: Test GitHub Actions

* Chore: Test GitHub Actions

* Chore: Test GitHub Actions

* Chore: Test GitHub Actions

* Chore: Test GitHub Actions

* Chore: Test GitHub Actions

* Chore: Test GitHub Actions

* Chore: Test GitHub Actions

* Chore: Test GitHub Actions

* Update: Ready For Release

* Update: Finalized Pipeline

---------

Co-authored-by: deejaygeroso <deejaygeroso@users.noreply.github.com>
Co-authored-by: Deejay Geroso <deejay.geroso@medirecords.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -10,7 +10,7 @@ permissions:
   contents: read
 
 jobs:
-  test-and-build:
+  build:
     runs-on: ubuntu-latest
     permissions:
       # Give the default GITHUB_TOKEN write permission to commit and push the
@@ -26,7 +26,62 @@ jobs:
       uses: actions/setup-node@v3
       with:
         node-version: '18.16.0'
-        registry-url: 'https://registry.npmjs.org'
+
+    - name: Install pNPM
+      run: npm install -g pnpm
+      
+    - name: Install Dependencies
+      run: pnpm install --frozen-lockfile
+
+    - name: Fetch Main Branch
+      run: git fetch origin main
+
+    # If project does not have changesets, then for now app will fail.
+    - name: Check Changeset
+      if: steps.changesets.outputs.hasChangesets == 'false'
+      run: exit 1
+
+    # Update Version of Packages based on Configured Changeset Version
+    - name: Changeset Version
+      run: npx changeset version
+
+    # Build Only the Packages that has changes detected or has its version updated.
+    - name: NX Build Affected Packages
+      run: pnpm affected:build
+
+    - name: Commit Changesets Update
+      run: |
+        git config --local user.email "deejaygeroso@gmail.com"
+        git config --local user.name "Deejay Geroso [BOT]"
+        git add .
+        git commit -m "Update: Changeset Version Applied"
+    
+    - name: Push changes
+      uses: ad-m/github-push-action@master
+      with:
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+        branch: main
+
+    # Upload dist directory to be reused by publish job.
+    - name: Upload dist Directory
+      uses: actions/upload-artifact@v3
+      with:
+        name: dist
+        path: dist
+
+  publish:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+      with:
+        fetch-depth: 2
+        
+    - name: Set up Node.js
+      uses: actions/setup-node@v3
+      with:
+        node-version: '18.16.0'
 
     - name: Install pNPM
       run: npm install -g pnpm
@@ -34,85 +89,17 @@ jobs:
     - name: Install Dependencies
       run: pnpm install --frozen-lockfile
 
-    - name: Fetch Main Branch
-      run: git fetch origin main
+    # Download dist directory generated from build job.
+    - name: Download dist Directory
+      uses: actions/download-artifact@v3
+      with:
+        name: dist
+        path: dist
 
-    - name: Create Changeset Release Pull Request
-      id: changesets
-      uses: changesets/action@v1
-      env:
-        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
+    - name: Modify Workspace File
+      run: sed -e "s|'packages\/|'dist/packages/|" pnpm-workspace.yaml > pnpm-new.yaml && mv pnpm-new.yaml pnpm-workspace.yaml
 
-    # If project does not have changesets, then for now app will fail.
-    - name: Check Changeset
-      if: steps.changesets.outputs.hasChangesets == 'false'
-      run: exit 1
-
-    # Build Only the Packages that has changes detected or has its version updated.
-    - name: NX Build Affected Packages
-      run: pnpm affected:build
-
-    # Copy all the required files to perform changeset publish.
-    - name: Copy Required Files used for Publishing Packages
-      run: cp -r package.json pnpm-workspace.yaml .changeset dist/publish
-
-    - name: Publish packages
+    - name: Publish
+      run: npx changeset publish
       env:
         NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
-      run: |
-        cd dist/publish/packages
-        for package in */; do
-          cd $package
-          pnpm publish --access public
-          cd ..
-        done
-
-    # # Copy Publish Package
-    # - name: Publish All Packages
-    #   run: |
-    #     cd dist/publish
-    #     npx changeset publish
-    #   env:
-    #     GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
-    #     NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
-    #     NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
-
-    # # Upload /dist directory to be reused by publish Job.
-    # - name: Upload /dist Directory
-    #   uses: actions/upload-artifact@v3
-    #   with:
-    #     name: dist
-    #     path: dist
-
-  # publish:
-  #   runs-on: ubuntu-latest
-  #   needs: test-and-build
-  #   steps:
-  #   - name: Set up Node.js
-  #     uses: actions/setup-node@v3
-  #     with:
-  #       node-version: '18.16.0'
-  #       registry-url: 'https://registry.npmjs.org'
-
-  #   # Download /dist directory from test-and-build Job.
-  #   - name: Download /dist Directory
-  #     uses: actions/download-artifact@v3
-  #     with:
-  #       name: dist
-  #       path: dist
-
-  #   - name: Check Status
-  #     run: |
-  #       ls -la
-  #       cd dist/publish
-  #       ls -la
-  #       npx changeset status
-
-  #   - name: Check List
-  #     run: ls -la
-
-    # - name: Publish Packages
-    #   run: npx changeset publish
-    #   env:
-    #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
-
