Chore: Test Pipeline

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -28,38 +28,38 @@ jobs:
       with:
         NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
 
-    # If project does not have changesets, then for now app will fail.
-    - name: Check Changeset
-      if: steps.changesets.outputs.hasChangesets == 'false'
-      run: exit 1
+    # # If project does not have changesets, then for now app will fail.
+    # - name: Check Changeset
+    #   if: steps.changesets.outputs.hasChangesets == 'false'
+    #   run: exit 1
 
-    # Update Version of Packages based on Configured Changeset Version
-    - name: Changeset Version
-      run: npx changeset version
+    # # Update Version of Packages based on Configured Changeset Version
+    # - name: Changeset Version
+    #   run: npx changeset version
 
-    # Build Only the Packages that has changes detected or has its version updated.
-    - name: NX Build Affected Packages
-      run: pnpm affected:build
+    # # Build Only the Packages that has changes detected or has its version updated.
+    # - name: NX Build Affected Packages
+    #   run: pnpm affected:build
 
-    - name: Commit Changesets Update
-      run: |
-        git config --local user.email "deejaygeroso@gmail.com"
-        git config --local user.name "Deejay Geroso [BOT]"
-        git add .
-        git commit -m "Update: Changeset Version Applied"
+    # - name: Commit Changesets Update
+    #   run: |
+    #     git config --local user.email "deejaygeroso@gmail.com"
+    #     git config --local user.name "Deejay Geroso [BOT]"
+    #     git add .
+    #     git commit -m "Update: Changeset Version Applied"
 
-    - name: Push changes
-      uses: ad-m/github-push-action@master
-      with:
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-        branch: main
+    # - name: Push changes
+    #   uses: ad-m/github-push-action@master
+    #   with:
+    #     github_token: ${{ secrets.GITHUB_TOKEN }}
+    #     branch: main
 
-    # Upload dist directory to be reused by publish job.
-    - name: Upload dist Directory
-      uses: actions/upload-artifact@v3
-      with:
-        name: dist
-        path: dist
+    # # Upload dist directory to be reused by publish job.
+    # - name: Upload dist Directory
+    #   uses: actions/upload-artifact@v3
+    #   with:
+    #     name: dist
+    #     path: dist
 
   publish:
     runs-on: ubuntu-latest
@@ -70,22 +70,27 @@ jobs:
       with:
         fetch-depth: 2
         
-    - name: Setup
-      uses: ./.github/actions/setup
+    - name: Restore pNPM cache
+      uses: actions/cache@v2
       with:
-        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
+        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
+        key: ${{ runner.job_id }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
+        restore-keys: ${{ runner.job_id }}-pnpm-store-
 
-    # Download dist directory generated from build job.
-    - name: Download dist Directory
-      uses: actions/download-artifact@v3
-      with:
-        name: dist
-        path: dist
+    - name: pNPM Version
+      run: pnpm --version
 
-    - name: Modify Workspace File
-      run: sed -e "s|'packages\/|'dist/packages/|" pnpm-workspace.yaml > pnpm-new.yaml && mv pnpm-new.yaml pnpm-workspace.yaml
+    # # Download dist directory generated from build job.
+    # - name: Download dist Directory
+    #   uses: actions/download-artifact@v3
+    #   with:
+    #     name: dist
+    #     path: dist
 
-    - name: Publish
-      run: npx changeset publish
-      env:
-        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
+    # - name: Modify Workspace File
+    #   run: sed -e "s|'packages\/|'dist/packages/|" pnpm-workspace.yaml > pnpm-new.yaml && mv pnpm-new.yaml pnpm-workspace.yaml
+
+    # - name: Publish
+    #   run: npx changeset publish
+    #   env:
+    #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
