Update: Test Publish (#9)
* Feature v1.0.0 alpha 6 (#6)

* Chore: Publish Testing

* Update: Automated Package Version Update

* Chore: Update packages

* Chore: Test Publishing

* Chore: Test Publishing

* Chore: Test Publishing

* Chore: Test Publishing

---------

Co-authored-by: deejaygeroso <deejaygeroso@users.noreply.github.com>

* Update: Automated Package Version Update

* Update: Packages

* Chore: Test Publishing

* Update: Automated Package Version Update

* Chore: Test Publishing

* Update: Changeset Origin

* Chore: Test Publishing

* Update: Automated Package Version Update

* Chore: Test Publishing

* Update: Automated Package Version Update

* Chore: Test Publishing

* Chore: Test Publishing

* Chore: Test Publishing

* Chore: Add script

* Chore: Update Pipeline

* Chore: Remove changesets

* Chore: Test Publish

* Chore: Test Publish

* Chore: Test Publish

* Update: Automated Package Version Update

* Chore: Test Changeset

* Chore: Test Changeset

* Chore: Test Changeset

* Chore: Test Changeset

* Chore: Test Changeset

* Chore: Test Changeset

* Chore: Test Changeset

* Chore: Test Changeset

* Chore: Test Changeset

* Chore: Test Changeset

* Chore: Test Changeset

* Chore: Test Changeset

* Chore: Test Changeset

* Chore: Add ci:publish

* Chore: Test Changeset

* Update: .npmrc

* Update: UI Updated

* Chore: Test without Token

* Update: Test without Token

* Chore: Add invalid token

* Update: Add Valid TOken

* Update: Package update

* Update: Release Pipeline Updated

* Update: Setup auth token

* Update: Remove duplicate

* Update: List all Files

* Update: Changeset Status

* Chore: Test

* Chore: Test

* Chore: Test

* Chore: Test

* Chore: Test

* Chore: Test

* Chore: Test

* Chore: Test Publish

* Chore: Add env file

* Chore: Test Publish

* Chore: Test Publish

* Chore: Test Publish

* Chore: Test Publish

* Update: Test Publish

---------

Co-authored-by: deejaygeroso <deejaygeroso@users.noreply.github.com>
Co-authored-by: Deejay Geroso <deejay.geroso@medirecords.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -3,7 +3,7 @@ name: Release Pipeline
 on:
   push:
     branches:
-      - release
+      - main
 
 permissions:
   id-token: write
@@ -21,62 +21,98 @@ jobs:
       uses: actions/checkout@v3
       with:
         fetch-depth: 2
-    - name: Set up Node.js
-      uses: actions/setup-node@v3
-      with:
-        node-version: '18.16.0'
-    - name: Install pNPM
-      run: npm install -g pnpm
-    - name: Install Dependencies
-      run: pnpm install
-    - name: Fetch Main Branch
-      run: git fetch origin main
-    # If system will detect no packages to be updated.
-    # Pipeline will fail.
-    # Build & Publish will not proceed.
-    - name: Check Changeset Status
-      run: npx changeset status
-    # Update Version of Packages based on Configured Changeset Version
-    - name: Changeset Version
-      run: npx changeset version
-    - name: Commit Changeset
-      uses: stefanzweifel/git-auto-commit-action@v4
-      with:
-        commit_message: "Update: Automated Package Version Update"
-        commit_options: "--no-gpg-sign"
-        commit_files: "./.changeset/**/*.md"
-    # Build Only the Packages that has changes detected or has its version updated.
-    - name: NX Build Affected Packages
-      run: pnpm affected:build
-    # Upload dist directory to be reused by publish job.
-    - name: Upload artifact
-      uses: actions/upload-artifact@v3
-      with:
-        name: dist
-        path: dist
-  publish:
-    runs-on: ubuntu-latest
-    needs: test-and-build
-    steps:
+
     - name: Set up Node.js
       uses: actions/setup-node@v3
       with:
         node-version: '18.16.0'
         registry-url: 'https://registry.npmjs.org'
-    # Download dist directory generated from build job.
-    - name: Download artifact
-      uses: actions/download-artifact@v3
-      with:
-        name: dist
-        path: dist
+
     - name: Install pNPM
       run: npm install -g pnpm
+
+    - name: Install Dependencies
+      run: pnpm install --frozen-lockfile
+
+    - name: Fetch Main Branch
+      run: git fetch origin main
+
+    - name: Create Changeset Release Pull Request
+      id: changesets
+      uses: changesets/action@v1
+      env:
+        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
+
+    # If project does not have changesets, then for now app will fail.
+    - name: Check Changeset
+      if: steps.changesets.outputs.hasChangesets == 'false'
+      run: exit 1
+
+    # Build Only the Packages that has changes detected or has its version updated.
+    - name: NX Build Affected Packages
+      run: pnpm affected:build
+
+    # Copy all the required files to perform changeset publish.
+    - name: Copy Required Files used for Publishing Packages
+      run: cp -r package.json pnpm-workspace.yaml .changeset dist/publish
+
     - name: Publish packages
       env:
-        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
+        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
       run: |
-        cd dist/packages
-        for dir in */; do
-          (cd "$dir" && pnpm publish --access public)
+        cd dist/publish/packages
+        for package in */; do
+          cd $package
+          pnpm publish --access public
+          cd ..
         done
+
+    # # Copy Publish Package
+    # - name: Publish All Packages
+    #   run: |
+    #     cd dist/publish
+    #     npx changeset publish
+    #   env:
+    #     GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
+    #     NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
+    #     NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
+
+    # # Upload /dist directory to be reused by publish Job.
+    # - name: Upload /dist Directory
+    #   uses: actions/upload-artifact@v3
+    #   with:
+    #     name: dist
+    #     path: dist
+
+  # publish:
+  #   runs-on: ubuntu-latest
+  #   needs: test-and-build
+  #   steps:
+  #   - name: Set up Node.js
+  #     uses: actions/setup-node@v3
+  #     with:
+  #       node-version: '18.16.0'
+  #       registry-url: 'https://registry.npmjs.org'
+
+  #   # Download /dist directory from test-and-build Job.
+  #   - name: Download /dist Directory
+  #     uses: actions/download-artifact@v3
+  #     with:
+  #       name: dist
+  #       path: dist
+
+  #   - name: Check Status
+  #     run: |
+  #       ls -la
+  #       cd dist/publish
+  #       ls -la
+  #       npx changeset status
+
+  #   - name: Check List
+  #     run: ls -la
+
+    # - name: Publish Packages
+    #   run: npx changeset publish
+    #   env:
+    #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
 
